marmotbakery/bakery/urls.py
#from asyncio.windows_events import NULL
from django.urls import path
from . import views
#from django.conf import settings 
#from django.conf.urls.static import static 
from django.shortcuts import render


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("placeorder", views.placeorder, name="placeorder"),
    path("myorders", views.myorders, name="myorders"),
    path("waitlist", views.waitlist, name="waitlist"),
    path("edit/<int:id>", views.edit, name="edit"),
    path("delete/<int:id>", views.delete, name="delete"),
    path("taskmanager", views.taskmanager, name="taskmanager"),
    path("metrics", views.metrics, name="metrics"),
    path("blogadmin", views.blogadmin, name="blogadmin"),
    path("deleteuser/<int:id>", views.deleteuser, name="deleteuser"),
    path("blog", views.blog, name="blog"),
    path("fileupload/<int:id>", views.fileupload, name="fileupload"),
    path("contententry/<int:blogid>", views.contententry, name="contententry"),
    path("createblog/<int:blogid>", views.createblog, name="createblog"),
    path("blogdetails/<int:blogid>", views.blogdetails, name="blogdetails"),
    path("deleteblog/<int:blogid>", views.deleteblog, name="deleteblog"),
    path("editblog/<int:blogid>", views.editblog, name="editblog"),
    
    path('bread_white', lambda request: render(request, 'bakery/bread_white.html')),
    path('bread_country', lambda request: render(request, 'bakery/bread_country.html')),
    path('bread_oats', lambda request: render(request, 'bakery/bread_oats.html')),
    path('bread_semolina', lambda request: render(request, 'bakery/bread_semolina.html')),
    path('bread_wholeweed', lambda request: render(request, 'bakery/bread_wholeweed.html')),
    path('bread_seeded', lambda request: render(request, 'bakery/bread_seeded.html')),
    path('bread_baguette', lambda request: render(request, 'bakery/bread_baguette.html')),
    path('bread_sweet', lambda request: render(request, 'bakery/bread_sweet.html')),

] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marmotbakery/marmotbakery/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bakery.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marmotbakery/bakery/models.py
import datetime
from typing_extensions import Concatenate
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.conf import settings

from bakery.forms import UserCreationForm


class User(AbstractUser):
    cancelations = models.IntegerField(default=0, null=False)
    def __str__(self):
        return f"{self.username}  {self.first_name} {self.last_name}"
    pass

class Orders(models.Model):
    breadType = (
        ('Бял Хляб', 'Бял Хляб'),
        ('Селски Хляб', 'Селски Хляб'),
        ('Хляб с Овесени Ядки', 'Хляб с Овесени Ядки'),
        ('Хляб Семолина', 'Хляб Семолина'),
        ('Пълнозърнест 100%', 'Пълнозърнест 100%'),
        ('Хляб със Семена', 'Хляб със Семена'),
        ('Багети 3х', 'Багети 3х'),
        ('Козунак', 'Козунак')
    )

    firstName = models.CharField(max_length=64)
    lastName = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    postCode = models.IntegerField()
    addressL1 = models.CharField(max_length=64)
    addressL2 = models.CharField(max_length=64)
    comment = models.CharField(max_length=256)
    breadType = models.CharField(max_length=64, choices=breadType)
    quantity = models.IntegerField(default=0, null=False)
    tel = models.IntegerField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    price = models.CharField(default=0, max_length=64)
    orderTime = models.DateTimeField(default=datetime.datetime.now)
    cumulative = models.IntegerField(default=0)
    cumulativeMax = models.IntegerField(default=0)
    brake = models.BooleanField(default=False)
    deliveryTime = models.DateTimeField(default=datetime.datetime.now)
    processed = models.IntegerField(default=0, null=False)
    active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.owner} >> {self.breadType} | {self.quantity}x | Delivery: {self.deliveryTime.date()}"
###
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin

class UserAdmin(BaseUserAdmin):
    add_form = UserCreationForm
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('email', 'first_name', 'last_name', 'is_bot_flag', 'password1', 'password2')}
        ),
    )
class Content(models.Model):
    content = models.TextField(null=True)
    blogid = models.IntegerField(default=0, null=False)
    number = models.IntegerField(default=0, null=False)
    isTitleImage = models.BooleanField(default=False)

class Image(models.Model):
    file = models.FileField(upload_to='', null=True, blank=True)
    filepath = models.CharField(null=True,max_length=999)
    filename = models.CharField(null=True, max_length=256)
    blogid = models.IntegerField(default=0, null=False)
    number = models.IntegerField(default=0, null=False)

class Blog(models.Model):
    blogid = models.IntegerField(default=0, null=False)

marmotbakery/bakery/views.py
from django.contrib.auth.decorators import user_passes_test
from collections import OrderedDict
import json
from .models import Blog, Content, User, Orders, Image
from bakery.forms import EditForm, PlaceOrderForm, FileForm
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.models.aggregates import Sum
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import date, datetime, timedelta, time
from django.db.models import Count
from django import template
import collections

register = template.Library()


def index(request):
    #
    # list all available contents for section My Column
    #
    allblogTitles={}
    for item in Content.objects.all():
        if (item.number == 0):
            allblogTitles[item.blogid] = item.content

    #
    return render(request, "bakery/index.html", {
        "allblogTitles": allblogTitles

    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "bakery/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "bakery/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "bakery/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "bakery/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "bakery/register.html")


@login_required
def placeorder(request):
    if request.method == 'POST':

        form = PlaceOrderForm(request.POST)

        if form.is_valid():
            if Orders.objects.all().count() == 0:
                cumuTemp = 0
                lastDeliveryDate = datetime.now().date() + timedelta(days=2)
                # if user has not ordered bread for 2-3 days. but it is not empty db so app gets lastdate
                # from db and ques. but we need 2 days to deliver, so it should be corrected with +2 days
            elif Orders.objects.all().count() is not 0 and Orders.objects.order_by('-deliveryTime').latest('deliveryTime').deliveryTime.date() < datetime.now().date() + timedelta(days=2):
                lastDeliveryDate = datetime.now().date() + timedelta(days=2)
                cumuTemp = Orders.objects.filter(processed=0).aggregate(
                    Sum('quantity'))['quantity__sum']
            else:
                cumuTemp = Orders.objects.filter(processed=0).aggregate(
                    Sum('quantity'))['quantity__sum']
                lastDeliveryDate = Orders.objects.order_by(
                    '-deliveryTime').latest('deliveryTime').deliveryTime.date()

            check = 10  # max daily capacity
            deliveryOn = lastDeliveryDate
            # check if daily orders exceed capacity of 10 and reshedule for day + 1
            #
            # special case, bug fix: no orders, user makes first order, then deletes it. cumuTemp is now None
            # and has to be corrected to the last cummulative value
            if cumuTemp is None:
                cumuTemp = Orders.objects.last().cumulative

            if cumuTemp >= check:
                cumuTemp = 0
                Orders.objects.all().update(processed=1)
                deliveryOn = lastDeliveryDate + timedelta(days=1)

            # check if order is received after 21:00 CET and  reshedule for day + 1
            # Sourdough has to be prepared for the next day. if order comes in after 21:00 CET
            # there will be no soudough for its completion => reshedule
            #
            # special case: additional check if delivery date is more than 2 days from now
            # if yes, order is not resheduled, because the sourdough planning can be made
            # 2 days in advance
            #
            if Orders.objects.all().count() != 0:
                lastDeliveryDate2 = Orders.objects.order_by(
                    "-id").values("deliveryTime").first()["deliveryTime"].date()
                #Orders.objects.all().update(processed=1)

                if datetime.now().hour > 21 and lastDeliveryDate2 > datetime.now().date() + timedelta(days=2):
                    if Orders.objects.order_by('-deliveryTime').latest('processed').processed == 1:
                        deliveryOn = lastDeliveryDate
                    else:
                        deliveryOn = lastDeliveryDate + timedelta(days=1)
                        Orders.objects.all().update(processed=1)
                        cumuTemp = 0

            # special case when user orders more than 1 bread and exceeds the capacity of 10
            # therefore the cumulative value and the delivery date have to be corrected
            # because the model accepts cumulative value greater than 10
            if cumuTemp + form.cleaned_data['quantity'] > check:
                cumuTemp = 0
                deliveryOn = Orders.objects.order_by(
                    '-deliveryTime').latest('deliveryTime').deliveryTime.date() + timedelta(days=1)
                Orders.objects.all().update(processed=1)
            
            #check if no orders longer than 2 days and zero
            #
            if Orders.objects.all().count() != 0:
                if Orders.objects.all().latest('deliveryTime').deliveryTime.date() + timedelta(2) < datetime.now().date():
                    cumuTemp=0
            

            order = Orders.objects.create(
                firstName=form.cleaned_data['firstName'],
                lastName=form.cleaned_data['lastName'],
                city=form.cleaned_data['city'],
                postCode=form.cleaned_data['postCode'],
                addressL1=form.cleaned_data['addressL1'],
                addressL2=form.cleaned_data['addressL2'],
                comment=form.cleaned_data['comment'],
                breadType=form.cleaned_data['breadType'],
                tel=form.cleaned_data['tel'],
                quantity=form.cleaned_data['quantity'],
                owner=request.user,
                price=form.cleaned_data['price'],
                orderTime=datetime.now().replace(microsecond=0),
                brake=False,
                deliveryTime=deliveryOn,
                cumulative=cumuTemp + form.cleaned_data['quantity']

            )
            order.save()

            return HttpResponseRedirect(reverse("waitlist"))
        else:
            lastOrder = Orders.objects.filter(
                owner=request.user).order_by('-id')[0]
            form = PlaceOrderForm(initial={'firstName': lastOrder.firstName,
                                           'lastName': lastOrder.lastName,
                                           'city': lastOrder.city,
                                           'postCode': lastOrder.postCode,
                                           'addressL1': lastOrder.addressL1,
                                           'addressL2': lastOrder.addressL2,
                                           'tel': lastOrder.tel
                                           })

        return render(request, 'bakery/placeorder.html', {'form': form})

    else:  # request is GET, render empty form
        checkUser = Orders.objects.filter(owner=request.user).count()
        if checkUser == 0:
            form = PlaceOrderForm()
        else:
            lastOrder = Orders.objects.filter(
                owner=request.user).order_by('-id')[0]
            form = PlaceOrderForm(initial={'firstName': lastOrder.firstName,
                                           'lastName': lastOrder.lastName,
                                           'city': lastOrder.city,
                                           'postCode': lastOrder.postCode,
                                           'addressL1': lastOrder.addressL1,
                                           'addressL2': lastOrder.addressL2,
                                           'tel': lastOrder.tel
                                           })

        if Orders.objects.all().count() == 0:
            maxDailyLeft = 10
        else:
            

            maxDailyLeft = Orders.objects.all().last().cumulative
            if maxDailyLeft == 10:
                maxDailyLeft = 10
            else:
                a=1
                #check if date is longer than 2 days ago, then zero the cumulative
                #
                if Orders.objects.all().latest('deliveryTime').deliveryTime.date() + timedelta(2) < datetime.now().date():
                    # update all past orders as processed
                    Orders.objects.all().update(processed=1)
                    #set new start value
                    maxDailyLeft = 10
                else:
                    maxDailyLeft = 10 - Orders.objects.all().last().cumulative

marmotbakery/bakery/templates/bakery/blogadmin.html
{% extends "bakery/layout.html" %}

{% block body %}
{% load static %}
<script src="{% static 'bakery/blogadmin.js' %}"></script>


<h2>Blog Admin</h2>

<h5>You can dynamically add content and image blocks to create you blog post.</h5>

<div style="justify-content: center; width: 100%; display: flex; flex-wrap: wrap;" class=" myCurrent">
    <div style="margin: 10px;  border: 1px solid lightgray;  width: 700px;">
        <div style="margin-bottom: 20px; padding: 10px; text-align: left    ; background: lightgray">
            <span style="margin: 0px 0px 10px 10px;">Builder elements: </span>
            <button class="contentbutton" style="margin: 0px 0px 10px 10px;">Add Content Block</button>
            
            <button  class=imagebutton style="margin: 0px 0px 10px 10px;">Add Image</button>
        <!-- </form> -->
        </div>

        <div class="create" style="margin: 10px">
            <p>Blog Id: <span id="blogid">{{id}}</span></p>
            <h5>Title:</h5>
            
            <input id="title" type="text" style="margin-bottom: 10px; width: 100%;" value="{{title}}">
            {% for ctnt in contents %}
            
            {%if ctnt.number != 0 %}

            {%if '/media' in ctnt.content %}
            <p class="number">{{ctnt.number}}</p>
            <img src="{{MEDIA_URL}}{{ctnt.content}}" alt="{{ctnt.content}}" width="100%">
            <br>
            {%else%}
            <p class="number">{{ctnt.number}}</p>
            <textarea id={{ctnt.number}} class="contentblock" style="resize: vertical; width: 100%; margin-bottom: 10px;"> {{ctnt.content}}</textarea>
            {%endif%}
            
            {%endif%}
            
            {% endfor %}

            <div class="last" style="text-align: center; margin-top: 10px; border: 1px dashed lightgray; width: 100%;">➕</div>
            <div style="width: 100%;">
                <p style="display: inline-block; margin-top: 50px;">Add builder elements by sing the buttons above...</p>
                <span style="display: inline-block; font-size: 50px;">☝🏻☝🏻☝🏻</span>
                
                <button disabled id="post" style="margin-top: 50px; float: right;">Post</button>
                <button id="save" style="margin-right: 10px; margin-top: 50px; float: right;">Save</button>
            </div>
        </div>
    </div>
    <div style="margin: 10px; border: 1px solid lightgray;  width: 300px;">
        <div style="margin-bottom: 20px; padding: 10px; text-align: center; background: lightgray">
            <h5>My Column</h5>
        </div>
        <div>
           
            {%for key, value in allblogTitles.items %}
            {% if forloop.counter|divisibleby:2 %}
            <a href='blogdetails/{{key}}' class="color1">{{value}}</a>
            {% else %}
            <a href='blogdetails/{{key}}' class="color2">{{value}}</a>
            {% endif %}
            
           
            
                
                
            {%endfor%}
        </div>
    </div>
</div>













{% endblock %}

marmotbakery/bakery/templates/bakery/blogdetails.html
{% extends "bakery/layout.html" %}

{% block body %}
{% load static %}
{% load custom_tags %}

<!-- {{blog|first}} -->

{% for item in blog%}

{%if item == blog|first%}
<h2>{{item.content}}</h2>
<hr>
{%else%}

{%if '/media' in item.content %}
<img src="{{MEDIA_URL}}{{item.content}}" alt="{{item.content}}" width="100%">
{%else%}
<p>{{item.content|markdown|safe}}</p>
{%endif%}
<br>
{%endif%}



{%endfor%}


{% endblock %}

marmotbakery/bakery/templates/bakery/bread_baguette.html
{% extends "bakery/layout.html" %}

{% block body %}
{% load static %}
{% load custom_tags %}
<h2>Багети 3 броя - 850г.</h2>

<div  style="width: 100%; justify-content: center; display: flex; flex-wrap: wrap;" class=" myCurrent">

<div class="breaddiv">

<br>
<h4>Съставки:</h4>
<hr>

<div style="display: inline-block; padding-left: 10px; vertical-align: top;">
    <p>• 100% бяло брашно (без ензими)</p>
    <p>• Вода</p>
    <p>• Сол</p>
    <p>• Натурален квас (брашно и вода)</p>
   
</div>
</div>

<div class="breaddiv">

    <br>
    <h4>Хранителни Стойности:</h4>
    <hr>
    
    <div style="display: inline-block; padding-left: 10px; vertical-align: top;">
        <table class="table table-bordered table-dark">
            <thead class="thead-light">
                <tr>
                    <th>
                        Хранителна Стойност
                    </th>
                    <th>
                        на 100 грама
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Енергийна стойност
                    </td>
                    <td>
                        220 kcal
                    </td>
                </tr>
                <tr>
                    <td>
                        Въглехидрати
                    </td>
                    <td>
                        44 г.
                    </td>
                    <tr>
                        <td>
                            Протеини
                        </td>
                        <td>
                            8.5 г.
                        </td>
                        <tr>
                            <td>
                                Мазнини
                            </td>
                            <td>
                                0.6 г.
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Сол
                            </td>
                            <td>
                                1.2 г.
                            </td>
                        </tr>
                        
                    </tr>
                </tr>

            </tbody>

        </table>
       
    </div>
       
    
    
    </div>


</div>

<a href="{% url 'index' %}">Обратно</a>

{% endblock %}

marmotbakery/bakery/templates/bakery/bread_semolina.html
{% extends "bakery/layout.html" %}

{% block body %}
{% load static %}
{% load custom_tags %}
<h2>Хляб Semolina - 850г.</h2>
<h4>Semola Rimacinata - италианска твърда пшеница.</h4>

<div  style="width: 100%; justify-content: center; display: flex; flex-wrap: wrap;" class=" myCurrent">

<div class="breaddiv">

<br>
<h4>Съставки:</h4>
<hr>

<div style="display: inline-block; padding-left: 10px; vertical-align: top;">
    <p>• 80% бяло брашно (без ензими)</p>
    <p>• 20% Semola Rimacinata</p>
    <p>• Вода</p>
    <p>• Сол</p>
    <p>• Натурален квас (брашно и вода)</p>
   
</div>
</div>

<div class="breaddiv">

    <br>
    <h4>Хранителни Стойности:</h4>
    <hr>
    
    <div style="display: inline-block; padding-left: 10px; vertical-align: top;">
        <table class="table table-bordered table-dark">
            <thead class="thead-light">
                <tr>
                    <th>
                        Хранителна Стойност
                    </th>
                    <th>
                        на 100 грама
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Енергийна стойност
                    </td>
                    <td>
                        222 kcal
                    </td>
                </tr>
                <tr>
                    <td>
                        Въглехидрати
                    </td>
                    <td>
                        45 г.
                    </td>
                    <tr>
                        <td>
                            Протеини
                        </td>
                        <td>
                            8.2 г.
                        </td>
                        <tr>
                            <td>
                                Мазнини
                            </td>
                            <td>
                                0.7 г.
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Сол
                            </td>
                            <td>
                                1.2 г.
                            </td>
                        </tr>
                        
                    </tr>
                </tr>

            </tbody>

        </table>
       
    </div>
       
    
    
    </div>


</div>

<a href="{% url 'index' %}">Обратно</a>

{% endblock %}

marmotbakery/bakery/templates/bakery/edit.html
{% extends "bakery/layout.html" %}

{% block body %}
{% load custom_tags %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelector('#id_breadType').addEventListener('change', function () {
            switch (document.getElementById('id_breadType').value) {
                case "Бял Хляб":
                    document.getElementById('id_price').value = "3.50"
                    break;
                case "Селски Хляб":
                    document.getElementById('id_price').value = "3.90"
                    break;
                case "Хляб с Овесени Ядки":
                    document.getElementById('id_price').value = "3.90"
                    break;
                case "Хляб Семолина":
                    document.getElementById('id_price').value = "4.50"
                    break;
                case "Пълнозърнест 100%":
                    document.getElementById('id_price').value = "5.90"
                    break;
                case "Хляб със Семена":
                    document.getElementById('id_price').value = "3.90"
                    break;
                case "Багети 3х":
                    document.getElementById('id_price').value = "4.90"
                    break;
                case "Козунак":
                    document.getElementById('id_price').value = "9.90"
                    break;

                default:
                    break;
            }
            //calculate total price on change
            var quantity = document.getElementById('id_quantity').value
            var price = document.getElementById('id_price').value
            var totalPrice = parseFloat(quantity) * parseFloat(price).toFixed(2)
            document.getElementById('totalPrice').innerHTML = totalPrice.toFixed(2)
        })
        var initialOrderCount = document.getElementById('id_quantity').value
        var allowedAdditional = document.getElementById('allowedAdditional').value

        document.getElementById('id_quantity').addEventListener('change', function () {
            //control how much bread can be additionally ordered
            var orderCount = document.getElementById('id_quantity').value
            var delta = initialOrderCount - orderCount

            //console.log(allowedAdditional)
            document.getElementById('dynamicAllowed').innerHTML = parseInt(delta) + parseInt(allowedAdditional)
            var orderCountArchive = document.getElementById('id_quantity').value - 1
            if (document.getElementById('dynamicAllowed').innerHTML < 0) {
                document.getElementById('dynamicAllowed').innerHTML = "0"
                document.getElementById('id_quantity').value = orderCountArchive
            }

            //calculate total price on change
            var quantity = document.getElementById('id_quantity').value
            var price = document.getElementById('id_price').value
            var totalPrice = parseFloat(quantity) * parseFloat(price).toFixed(2)
            document.getElementById('totalPrice').innerHTML = totalPrice.toFixed(2)
        })

    })

</script>


<h2>Edit Your Order</h2>
<input type="hidden" id="allowedAdditional" value={{allowedAdditional}}>

<div style="width: 100%; display: flex; flex-wrap: wrap;" class=" myCurrent">
    {% for order in orders %}

    {% if order.id == id %}
    <form action="{{order.id}}" method="post">
        {% csrf_token %}
    <div style="width: 300px; background: rgb(221, 228, 221); border-radius: 10px; padding: 10px; margin: 5px;">

        <h3>
            <select id="id_breadType" name="breadType">
                {% for x, y in form.fields.breadType.choices %}
                <option value="{{ x }}" {% if order.breadType == x %} selected {% endif %}>{{ y }}</option>
                {% endfor %}
            </select>

        </h3>
        <hr>
        <div>
            <p style="margin: 5px 0;">Количество:
                {{form.quantity}}
                <span id="noMoreAcc" style="color: darkorange;"> оставащи за деня: <span
                        id="dynamicAllowed">{{allowedAdditional}}</span></span>
            </p>
            <p style="margin: 5px 0;">Готов на: {{order.deliveryTime.date}}</p>
            <p style="margin: 5px 0;">Единична Цена: {{form.price}}</p>


        </div>
        <div>
            <p>Общя Цена: <span id="totalPrice">{{order.price|removeDollar | multiply:order.quantity }}</span></p>
        </div>
        <hr>

        <div>

            <input style="margin-top: 10px;" type="submit" value="Save"> | <a id=c{{order.id}} href="{% url 'myorders' %}">Отказ</a> | <a
                id=d{{order.id}} href="/delete/{{order.pk}}">Изтрий</a>

        </div>

    </div>
    </form>
    {% else %}
    <div
        style="opacity: 0.4; width: 300px; background: rgb(221, 228, 221); border-radius: 10px; padding: 10px; margin: 5px;">

        <h3>{{order.breadType}}</h3>
        <hr>
        <div>
            <p style="margin: 5px 0;">Количество: {{order.quantity}}</p>
            <p style="margin: 5px 0;">Готов на: {{order.deliveryTime.date}}</p>
            <p style="margin: 5px 0;">Единична Цена: {{order.price}}</p>


        </div>
        <div>
            <p>Обща Цена: {{order.price|removeDollar | multiply:order.quantity}}</p>
        </div>
        <hr>

        <div>

            <a id=e{{order.id}} href="{{order.pk}}">Edit</a> | <a id=d{{order.id}} href="/delete/{{order.pk}}">Delete</a>

        </div>

    </div>
    {% endif%}


    {% endfor %}



    {% endblock %}

marmotbakery/bakery/templates/bakery/fileupload.html
{% extends "bakery/layout.html" %}

{% block body %}
    <h2>File Upload</h2>

    <form action="/fileupload/{{id}}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for entry in form %}
           <div>
                {{ entry.label_tag }}
           </div>
           <div>
               {{entry}}
           </div>
        {% endfor %}
        <br>
        
        <button style="margin-top: 10px;">
            Save!
        </button>
        
    </form>
    <hr>

    <form style="margin-top: 10px;" action="/blogadmin">
        <input type="submit" value="Cancel" />
    </form>

 

{% endblock %}

marmotbakery/bakery/templates/bakery/login.html
{% extends "bakery/layout.html" %}

{% block body %}

    <h2>Вход</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Вход">
    </form>

    Нямате регистрация? <a href="{% url 'register' %}">Регистрирайте се тук.</a>

{% endblock %}